# Generated by Django 3.2.16 on 2022-10-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted_reason', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('number', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('names', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Apellidos y nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('gender', models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Femenino'), ('Other', 'Otro')], default='Other', max_length=10, verbose_name='Genero')),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Dirección')),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cod. postal')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('cell_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('email_alternate', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email alterno')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.syscountries', verbose_name='Pais')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sysnationality', verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ('names',),
            },
        ),
        migrations.CreateModel(
            name='StudentRegisters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted_reason', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('number', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('date_issue', models.DateTimeField(blank=True, null=True)),
                ('code_international_register', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Internacional de Registro')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.certificates', verbose_name='Certificado')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.syscountries', verbose_name='Pais')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions', verbose_name='Institución')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.students', verbose_name='Estudiante')),
                ('type_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.instyperegistries', verbose_name='Tipo de registro')),
            ],
            options={
                'verbose_name': 'Estudiante Registro',
                'verbose_name_plural': 'Estudiante Registros',
                'ordering': ('created_at',),
            },
        ),
    ]
