# Generated by Django 3.2.16 on 2022-10-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInstitutionQuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted_reason', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('number', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('date_issue', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Emision')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Subtotal')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Descuento')),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Impuesto')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Total')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Orden institucion cupo',
                'verbose_name_plural': 'Orden institucion cupos',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='OrderInstitutionQuotaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted_reason', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('quotas', models.IntegerField(blank=True, default=0, null=True, verbose_name='cupos')),
                ('values', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('quota_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cupo Saldo')),
                ('order_institution_quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.orderinstitutionquotas', verbose_name='Orden institucion cupo')),
                ('type_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.instyperegistries', verbose_name='Tipo de registro')),
            ],
            options={
                'verbose_name': 'Orden institucion cupo detalle',
                'verbose_name_plural': 'Orden institucion cupo detalles',
                'ordering': ('order_institution_quota',),
            },
        ),
    ]
