# Generated by Django 3.2.16 on 2022-10-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted_reason', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('number', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('names', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Apellidos y nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Dirección')),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cod. postal')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('cell_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('email_alternate', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email alterno')),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='AdvisersCommissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted_reason', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('number', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('date_current', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('date_issue', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Comisión')),
            ],
            options={
                'verbose_name': 'Asesor Comisión',
                'verbose_name_plural': 'Asesor Comisiones',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='PaymentAdviserCommissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted_reason', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('number', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('date_payment', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Mes')),
                ('values', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Pago Asesor Comisión',
                'verbose_name_plural': 'Pago Asesor Comisiones',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='PaymentAdviserCommissionsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('deleted_reason', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Comisión')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Pago Asesor Comisión Detalle',
                'verbose_name_plural': 'Pago Asesor Comisión Detalles',
            },
        ),
    ]
