# Generated by Django 3.2.16 on 2022-10-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('system', '0001_initial'),
        ('advisers', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentadvisercommissionsdetails',
            name='order_institution_quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.orderinstitutionquotas', verbose_name='Orden institucion Cupo'),
        ),
        migrations.AddField(
            model_name='paymentadvisercommissionsdetails',
            name='payment_adviser_commissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisers.paymentadvisercommissions', verbose_name='Pago Asesor Comisión'),
        ),
        migrations.AddField(
            model_name='paymentadvisercommissionsdetails',
            name='type_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.instyperegistries', verbose_name='Tipo de registro'),
        ),
        migrations.AddField(
            model_name='paymentadvisercommissions',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisers.advisers', verbose_name='Asesor'),
        ),
        migrations.AddField(
            model_name='adviserscommissions',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisers.advisers', verbose_name='Asesor'),
        ),
        migrations.AddField(
            model_name='adviserscommissions',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='advisers',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.syscountries', verbose_name='Pais'),
        ),
    ]
